[profile.default]
solc = "0.8.19"
optimizer = true
optimizer_runs = 9_999_999

# Configure remappings
remappings = [
  "@std=lib/forge-std/src/",
  "@solbase=lib/solbase/"
]

[profile.intense.fuzz]
runs = 5_000

[fmt]
line_length = 100